### PR TITLE
version 2.3

### PR DESCRIPTION
**Pull request by cvvergara**
# New Features

```
  --attributes                          Include attributes information.
  --tags                                Include tag information.
  --chunk arg (=20000)                  Exporting chunk size.
  --no-index                            Do not create indexes (Use when indexes
                                        are already created)
```

Version
```
$ osm2pgrouting -v
This is osm2pgrouting Version 2.3
```

Options:
```
osm2pgrouting --help
Allowed options:

Help:
  --help                Produce help message for this version.
  -v [ --version ]      Print version string

General:
  -f [ --file ] arg                     REQUIRED: Name of the osm file.
  -c [ --conf ] arg (=/usr/share/osm2pgrouting/mapconfig.xml)
                                        Name of the configuration xml file.
  --schema arg                          Database schema to put tables.
                                          blank: defaults to default schema 
                                                dictated by PostgreSQL 
                                                search_path.
  --prefix arg                          Prefix added at the beginning of the 
                                        table names.
  --suffix arg                          Suffix added at the end of the table 
                                        names.
  --postgis                             Install postgis if not found.
  --addnodes                            Import the osm_nodes, osm_ways & 
                                        osm_relations tables.
  --attributes                          Include attributes information.
  --tags                                Include tag information.
  --chunk arg (=20000)                  Exporting chunk size.
  --clean                               Drop previously created tables.
  --no-index                            Do not create indexes (Use when indexes
                                        are already created)

Database options:
  -d [ --dbname ] arg            Name of your database (Required).
  -U [ --username ] arg          Name of the user, which have write access to 
                                 the database.
  -h [ --host ] arg (=localhost) Host of your postgresql database.
  -p [ --port ] arg (=5432)      db_port of your database.
  -W [ --password ] arg          Password for database access.

```

Tested on Travis and Jenkins

### CODE REVIEW

**Comment by cvvergara** [comment]
@dersvenhesse 
I wonder if you can test develop branch for mac, before I merge into master

**Comment by dersvenhesse** [comment]
@cvvergara Thad would be much easier with a pre-release (alpha, beta, whatever). But I'd say you can just merge and release the final version and I will look into bringing this into homebrew afterwards. There will be some deployment tests anyhow before releasing this.

**Comment by cvvergara** [comment]
@dersvenhesse 
On this one we don't do alpha, beta etc when the "minor" version changes. (we do it on pgRouting because there is a huge rewrite going on there)
But well, then, after I release 2.3.0 then if something happens we can create a 2.3.1 that works for mac.

**Comment by cvvergara** [comment]
@dersvenhesse 
@dkastl 
@robe2 
I created the tag
https://github.com/pgRouting/osm2pgrouting/releases/tag/v2.3.0

**Comment by dersvenhesse** [comment]
I created a PR for Homebrew: https://github.com/Homebrew/homebrew-core/pull/19346.

**Pull request merged**
