### PR TITLE
Add support for alternative schema location of postgis

### PR DESCRIPTION
**Pull request by prevostc**

### CODE REVIEW

**Comment by woodbri** [comment]
Can this be done less intrusively by appending the postgis schema to the search_path ?

**Comment by robe2** [comment]
He might be talking about putting data in a schema other than public or the default user's schema.  I already added support for that in osm2pgrouting 2.1.  

https://github.com/pgRouting/osm2pgrouting/tree/osm2pgrouting-2.1.0-alpha

Though it seems my update to the Readme.md didn't get carried over (I might have forgotten to commit)

As far as where postgis is located, 
1) There can only be one postgis installed in a database.  If you have more, you've got serious problems.
2) if postgis isn't in the search_path of the database, many postgis functions will not work at all.  So I think it's a safe bet to assume that if you have a functioning system, where postgis is located is already in your database search path.

**Comment by woodbri** [comment]
The patch is adding and explicit postgis schema name in front of the postgis/pgrouting functions. So this has a few problems:
1. if postgis and pgrouting are not in the same schema this patch will fail
2. clearly explicitly setting schema.functionname() is not the way to solve this problem
3. into pgRouting:master from prevostc:master - this should not be against master 

The user needs to just set the search path on the database like:
```
-- the database search_path for new connections
alter database "dbname" set search_path to "pgrouting_schema", "postgis_schema", public;
-- or set the search_path for the current connection
set search_path to "pgrouting_schema", "postgis_schema", public;
-- or do both
```
But this sounds more like user error and not a poull request we want to accept.

**Comment by prevostc** [comment]
@woodbri : I understand these problems and I agree with all 3.

I'm not sure although that it's the way search_path was designed to be used for. To me, the ability to set an extension's schema should be enough for extensions to work together and external tools shouldn't expect extensions to be searchable.

**Comment by dkastl** [comment]
I like the proposal of @woodbri , but there could be one case, where this is not a good idea: when there are tables with the same name in different schemas. And I think this can be one reason to have multiple schemas. And setting the search path will just cause troubles in this case, I think.

**Comment by robe2** [comment]
I think we are talking about two things here.  Like I said I already implemented schema support for osm2pgrouting 2.1.0 on

output looks like this:
```

Help:
  --help                                Produce help message for this version.

General:
  -f [ --file ] arg                     Name of your osm file (Required).
  -c [ --conf ] arg (=/usr/share/osm2pgrouting/mapconfig.xml)
                                        Name of your configuration xml file.
  --schema arg                          Database schema to put tables. If left
                                        blank, defaults to default schema
                                        dictated by Postgresql search_path.
  --prefix arg                          Prefix added at the beginning of table
                                        names.
  --suffix arg                          Suffix added at the end of table names.
  -s [ --skipnodes ] arg (=1)           When true: don't import the osm_nodes
                                        table.
  --clean arg (=0)                      When true: Drop previously created
                                        tables.

Database options:
  -d [ --dbname ] arg                   Name of your database (Required).
  -u [ --user ] arg (=postgres)         Name of the user, which have write
                                        access to the database.
  -h [ --host ] arg (=localhost)        Host of your postgresql database.
  -p [ --db_port ] arg (=5432)          db_port of your database.
  --passwd arg                          Password for database access.

```

See the --schema arg option?  So that takes care of tables residing in different schemas and you want to load into a particular schema.


As far as extensions go, you can only install an extension once in a database.  

So doing something like:

```
CREATE EXTENSION pgrouting schema public;

-- this one would error out
CREATE EXTENSION pgrouting schema postgis;

```

Thus it makes not sense to have pgrouting be told where the extension is since it should be part of the search_path already if you expect to be able to use pgrouting and postgis.  In face as @woodbri noted, pgRouting and postgis may be in different schemas, so setting one doesn't help the other case of having to find pgRouting functions.

**Comment by woodbri** [comment]
This pull request, is only taking the new arguments value and then modifying the calls to AddGeometryColumn() by prepending the new schema to that function and doing the same to pgr_createtopology() call. Since one function is in the postgis extension and the other function is in the pgRouting extension, and these extensions do not have to be installed in the same schema, this patch is broken. Also, the purpose of search_path is so you can find your extensions, and it they are not in the search path, then all the pgrouting functions that pgr_createtopology() calls internally will not be found and it will fail anyway. IE: prepending schema to pgr_createtopology() does not fix the problem.

None of this has anything to do with where tables are created. And if the user does not know how to setup a database correctly, then this is not a pgrouting problem anyway. Of course if they ask I'm sure we will try to help by explaining best practices or pointing them to the workshop.

This pull request should not be merged. I'm closing this. If someone thinks there is a reason to keep it open then reopen it and state why, or better yet create a new ticket for what you would like as a feature in a future release.

**Comment by prevostc** [comment]
@woodbri Thanks for your time. I installed pgRouting and Pogtgis in a specific schema and then ran into some osm2pgrouting issues because it could not find the AddGeometryColumn function. I thought this patch would solve this problem but did ran into the pgr_createtopology internal call problem and the only way to solve this is to use search_path. I'm sorry that I submitted this patch too early, I should have tested it more before submit. 

I'm still disappointed regarding the postgresql extension system though. I can create any extensions in any schema but if this extension has dependencies it always fail. Sadly, I can't find of a solution that don't require a full rewrite of all postgresql extensions.

**Comment by woodbri** [comment]
No worries. While you can install in any schema, it does not always make sense to do that. I install all my extension in public because that is easy and always works, but I never put any of my data in public. Data always goes into other schemas, this make is easy to dump/restore the database. you should be able to install like this:
```
create schema postgis;
create extension postgis with schema postgis;
set search_path postgis, public;
create schema pgrouting;
create extension pgrouting with schema pgrouting;
alter database "dbname"  set search_path to postgis, pgrouting, public;
set search_path to postgis, pgrouting, public;
```

**Comment by robe2** [comment]
Yah I've been hoping for a while postgres would implement some logic that if you say an extension needs another extension, the search path of the other extensions can be included and also the functions when they are called would automatically include the extension schema (after all it forces you to install an extension in only one schema anyway).

It's more of an issue with restore since restore always sets its search path to the table being restored + pg_catalog so we've gotten bitten with that in postgis raster land for functions that rely on other postgis functions. and that are used in constraint checks.  

anywho we do things a bit differently from @woodbri .  We install our extensions in specific schema like postgis/contrib (some frameworks like rube and django I think also do that, so you may end up with that if you use their glue to build your db). We throw all our data/user functions in public unless we need to logically segregate data (or segregate functions we use across clients). 

 In the end it's all the same and since extensions don't get backed up (except for data marked as user changeable), it doesn't affect your ease of restoring unto a new postgis/pgrouting where you keep your data/function.  It just provides a bit of sanity to not have your user functions and tables mixed in with the 1000+ of postgis and the 30-70+ of pgrouting.functions and stuff.

**Comment by woodbri** [comment]
Yeah, the basic idea is the same, separate the extension stuff from the application stuff. Any application specific functions also go in the application schema like "data" in my case, so I can find my functions with wading through all the extension functions. I also always dump my databases using plain format, that way can setup the database and extensions on a new server and set up the search_path, then restore using psql. Also if I have to tweak my dump, a simple perl script is usually all I need to mangle the dump file to do what I need it to.

**Pull request closed without merging**
