### PR TITLE
Foreign keys

### PR DESCRIPTION
**Pull request by ldesousa**
Adds a new method to Export2DB that creates foreign keys for all tables except ways after the topology is created. When the topology is created primary key and foreign keys are added to the ways table, as so foreign keys in other tables referencing ways.

Still missing a foreign for the way_id field in the relations_way table. Not yet clear what is this field is supposed to be referencing.

The nodes table is not referenced; not clear why either.

### CODE REVIEW

**Comment by cvvergara** [comment]
@ldesousa 
I am in the process of releasing the version v2.1, 
but once v2.1 is released we can talk about it.
I also think relating the <edge_table> with the other tables specially the <edge_table>_pgr_vertices is also important,

**Comment by cvvergara** [comment]
@ldesousa 
Hello, sorry for the delay. 
I was trying to merge to develop.
You started to add this feature from an older version of osm2pgrouting.
I merged you code to the new version of osm2pgrouting, and some fixes are needed for it to work.
I get:
```
7primary keys for ways failed: ERROR:  multiple primary keys for table "ways" are not allowed

7foreign keys for classes failed:ERROR:  relation "classes" does not exist

7foreign keys for way_tag failed: ERROR:  relation "way_tag" does not exist

7foreign keys for relations failed: ERROR:  relation "relations" does not exist

7foreign keys for ways failed: ERROR:  relation "classes" does not exist
```
maybe because, for example, here:  
https://github.com/pgRouting/osm2pgrouting/blob/ldesousa-fkeys/src/Export2DB.cpp#L64
the primary keys are already taken care of. ;)

Now the names of the tables can have a schema, a prefix and a suffix, so for example:
```
addSchema( "osm_way_classes" ) 
addSchema( full_table_name("ways"))
```

I created a branch: ldesousa-fkeys
To have this branch in you clone on your computer (You need  `upstream` pointing to osm2pgrouting [instructions](https://help.github.com/articles/configuring-a-remote-for-a-fork/))
```
git fetch upstream
git checkout ldesousa-fkeys
git push --set-upstream origin ldesousa-fkeys
```

**Comment by ldesousa** [comment]
Hi there Vicky,

I coded this over 2 years ago, it certainly was not meant to be merged to the current code base.

Presently I can not work on it, the little free time I have is employed on getting PyWPS 4.0 released. Maybe someone else could pick it up?

Regards,

Luís

**Comment by cvvergara** [comment]
@ldesousa 
I'll pick it up.

**Comment by cvvergara** [comment]
@ldesousa 
made the changes, if you want to try it out its in develop

**Pull request merged**
